/*
Oracle
*/
SELECT A.CONTEST_ID, A.HACKER_ID, A.NAME, 
        SUM(E.TOTAL_SUBMISSIONS) AS TOTAL_SUBMISSIONS, 
        SUM(E.TOTAL_ACCEPTED_SUBMISSIONS) AS TOTAL_ACCEPTED_SUBMISSIONS,
        SUM(D.TOTAL_VIEWS) AS TOTAL_VIEWS,
        SUM(D.TOTAL_UNIQUE_VIEWS) AS TOTAL_UNIQUE_VIEWS
FROM CONTESTS A
LEFT JOIN COLLEGES B
    ON A.CONTEST_ID = B.CONTEST_ID
LEFT JOIN CHALLENGES C
    ON B.COLLEGE_ID = C.COLLEGE_ID 
LEFT JOIN (SELECT CHALLENGE_ID, SUM(TOTAL_VIEWS) AS TOTAL_VIEWS, 
                  SUM(TOTAL_UNIQUE_VIEWS) AS TOTAL_UNIQUE_VIEWS
           FROM VIEW_STATS
           GROUP BY CHALLENGE_ID) D 
    ON C.CHALLENGE_ID = D.CHALLENGE_ID 
LEFT JOIN (SELECT CHALLENGE_ID, SUM(TOTAL_SUBMISSIONS) AS TOTAL_SUBMISSIONS, 
                  SUM(TOTAL_ACCEPTED_SUBMISSIONS) AS TOTAL_ACCEPTED_SUBMISSIONS
           FROM SUBMISSION_STATS
           GROUP BY CHALLENGE_ID) E
    ON C.CHALLENGE_ID = E.CHALLENGE_ID
GROUP BY A.CONTEST_ID, A.HACKER_ID, A.NAME
HAVING (SUM(E.TOTAL_SUBMISSIONS) 
        + SUM(E.TOTAL_ACCEPTED_SUBMISSIONS) 
        + SUM(D.TOTAL_VIEWS) 
        + SUM(D.TOTAL_UNIQUE_VIEWS)) > 0 
ORDER BY A.CONTEST_ID;
